// Auto-generated. Do not edit!

// (in-package brl_pxh_api.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CartTrajGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.x = null;
      this.z = null;
      this.roll = null;
      this.pitch = null;
      this.moving_time = null;
      this.wp_moving_time = null;
      this.wp_accel_time = null;
      this.wp_period = null;
    }
    else {
      if (initObj.hasOwnProperty('x')) {
        this.x = initObj.x
      }
      else {
        this.x = 0.0;
      }
      if (initObj.hasOwnProperty('z')) {
        this.z = initObj.z
      }
      else {
        this.z = 0.0;
      }
      if (initObj.hasOwnProperty('roll')) {
        this.roll = initObj.roll
      }
      else {
        this.roll = 0.0;
      }
      if (initObj.hasOwnProperty('pitch')) {
        this.pitch = initObj.pitch
      }
      else {
        this.pitch = 0.0;
      }
      if (initObj.hasOwnProperty('moving_time')) {
        this.moving_time = initObj.moving_time
      }
      else {
        this.moving_time = 0.0;
      }
      if (initObj.hasOwnProperty('wp_moving_time')) {
        this.wp_moving_time = initObj.wp_moving_time
      }
      else {
        this.wp_moving_time = 0.0;
      }
      if (initObj.hasOwnProperty('wp_accel_time')) {
        this.wp_accel_time = initObj.wp_accel_time
      }
      else {
        this.wp_accel_time = 0.0;
      }
      if (initObj.hasOwnProperty('wp_period')) {
        this.wp_period = initObj.wp_period
      }
      else {
        this.wp_period = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CartTrajGoal
    // Serialize message field [x]
    bufferOffset = _serializer.float32(obj.x, buffer, bufferOffset);
    // Serialize message field [z]
    bufferOffset = _serializer.float32(obj.z, buffer, bufferOffset);
    // Serialize message field [roll]
    bufferOffset = _serializer.float32(obj.roll, buffer, bufferOffset);
    // Serialize message field [pitch]
    bufferOffset = _serializer.float32(obj.pitch, buffer, bufferOffset);
    // Serialize message field [moving_time]
    bufferOffset = _serializer.float32(obj.moving_time, buffer, bufferOffset);
    // Serialize message field [wp_moving_time]
    bufferOffset = _serializer.float32(obj.wp_moving_time, buffer, bufferOffset);
    // Serialize message field [wp_accel_time]
    bufferOffset = _serializer.float32(obj.wp_accel_time, buffer, bufferOffset);
    // Serialize message field [wp_period]
    bufferOffset = _serializer.float32(obj.wp_period, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CartTrajGoal
    let len;
    let data = new CartTrajGoal(null);
    // Deserialize message field [x]
    data.x = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [z]
    data.z = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [roll]
    data.roll = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [pitch]
    data.pitch = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [moving_time]
    data.moving_time = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [wp_moving_time]
    data.wp_moving_time = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [wp_accel_time]
    data.wp_accel_time = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [wp_period]
    data.wp_period = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 32;
  }

  static datatype() {
    // Returns string type for a message object
    return 'brl_pxh_api/CartTrajGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'db3424a7a9bc8795db95e0a23d1c2e25';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Goal
    float32 x
    float32 z
    float32 roll
    float32 pitch
    float32 moving_time
    float32 wp_moving_time
    float32 wp_accel_time
    float32 wp_period
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CartTrajGoal(null);
    if (msg.x !== undefined) {
      resolved.x = msg.x;
    }
    else {
      resolved.x = 0.0
    }

    if (msg.z !== undefined) {
      resolved.z = msg.z;
    }
    else {
      resolved.z = 0.0
    }

    if (msg.roll !== undefined) {
      resolved.roll = msg.roll;
    }
    else {
      resolved.roll = 0.0
    }

    if (msg.pitch !== undefined) {
      resolved.pitch = msg.pitch;
    }
    else {
      resolved.pitch = 0.0
    }

    if (msg.moving_time !== undefined) {
      resolved.moving_time = msg.moving_time;
    }
    else {
      resolved.moving_time = 0.0
    }

    if (msg.wp_moving_time !== undefined) {
      resolved.wp_moving_time = msg.wp_moving_time;
    }
    else {
      resolved.wp_moving_time = 0.0
    }

    if (msg.wp_accel_time !== undefined) {
      resolved.wp_accel_time = msg.wp_accel_time;
    }
    else {
      resolved.wp_accel_time = 0.0
    }

    if (msg.wp_period !== undefined) {
      resolved.wp_period = msg.wp_period;
    }
    else {
      resolved.wp_period = 0.0
    }

    return resolved;
    }
};

module.exports = CartTrajGoal;
