// Auto-generated. Do not edit!

// (in-package brl_pxh_api.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ConstPoseGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.moving_time = null;
    }
    else {
      if (initObj.hasOwnProperty('moving_time')) {
        this.moving_time = initObj.moving_time
      }
      else {
        this.moving_time = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ConstPoseGoal
    // Serialize message field [moving_time]
    bufferOffset = _serializer.float32(obj.moving_time, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ConstPoseGoal
    let len;
    let data = new ConstPoseGoal(null);
    // Deserialize message field [moving_time]
    data.moving_time = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'brl_pxh_api/ConstPoseGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '111da1849bb8c0b990e33aba3fa0e62c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Goal
    float32 moving_time
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ConstPoseGoal(null);
    if (msg.moving_time !== undefined) {
      resolved.moving_time = msg.moving_time;
    }
    else {
      resolved.moving_time = 0.0
    }

    return resolved;
    }
};

module.exports = ConstPoseGoal;
