; Auto-generated. Do not edit!


(cl:in-package brl_pxh_api-msg)


;//! \htmlinclude ConstPoseGoal.msg.html

(cl:defclass <ConstPoseGoal> (roslisp-msg-protocol:ros-message)
  ((moving_time
    :reader moving_time
    :initarg :moving_time
    :type cl:float
    :initform 0.0))
)

(cl:defclass ConstPoseGoal (<ConstPoseGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ConstPoseGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ConstPoseGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name brl_pxh_api-msg:<ConstPoseGoal> is deprecated: use brl_pxh_api-msg:ConstPoseGoal instead.")))

(cl:ensure-generic-function 'moving_time-val :lambda-list '(m))
(cl:defmethod moving_time-val ((m <ConstPoseGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader brl_pxh_api-msg:moving_time-val is deprecated.  Use brl_pxh_api-msg:moving_time instead.")
  (moving_time m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ConstPoseGoal>) ostream)
  "Serializes a message object of type '<ConstPoseGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'moving_time))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ConstPoseGoal>) istream)
  "Deserializes a message object of type '<ConstPoseGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'moving_time) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ConstPoseGoal>)))
  "Returns string type for a message object of type '<ConstPoseGoal>"
  "brl_pxh_api/ConstPoseGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ConstPoseGoal)))
  "Returns string type for a message object of type 'ConstPoseGoal"
  "brl_pxh_api/ConstPoseGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ConstPoseGoal>)))
  "Returns md5sum for a message object of type '<ConstPoseGoal>"
  "111da1849bb8c0b990e33aba3fa0e62c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ConstPoseGoal)))
  "Returns md5sum for a message object of type 'ConstPoseGoal"
  "111da1849bb8c0b990e33aba3fa0e62c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ConstPoseGoal>)))
  "Returns full string definition for message of type '<ConstPoseGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%float32 moving_time~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ConstPoseGoal)))
  "Returns full string definition for message of type 'ConstPoseGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%float32 moving_time~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ConstPoseGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ConstPoseGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ConstPoseGoal
    (cl:cons ':moving_time (moving_time msg))
))
