; Auto-generated. Do not edit!


(cl:in-package brl_pxh_api-msg)


;//! \htmlinclude GripperMotionGoal.msg.html

(cl:defclass <GripperMotionGoal> (roslisp-msg-protocol:ros-message)
  ((delay
    :reader delay
    :initarg :delay
    :type cl:float
    :initform 0.0))
)

(cl:defclass GripperMotionGoal (<GripperMotionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GripperMotionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GripperMotionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name brl_pxh_api-msg:<GripperMotionGoal> is deprecated: use brl_pxh_api-msg:GripperMotionGoal instead.")))

(cl:ensure-generic-function 'delay-val :lambda-list '(m))
(cl:defmethod delay-val ((m <GripperMotionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader brl_pxh_api-msg:delay-val is deprecated.  Use brl_pxh_api-msg:delay instead.")
  (delay m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GripperMotionGoal>) ostream)
  "Serializes a message object of type '<GripperMotionGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'delay))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GripperMotionGoal>) istream)
  "Deserializes a message object of type '<GripperMotionGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'delay) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GripperMotionGoal>)))
  "Returns string type for a message object of type '<GripperMotionGoal>"
  "brl_pxh_api/GripperMotionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GripperMotionGoal)))
  "Returns string type for a message object of type 'GripperMotionGoal"
  "brl_pxh_api/GripperMotionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GripperMotionGoal>)))
  "Returns md5sum for a message object of type '<GripperMotionGoal>"
  "083c040d329e25abca99d1f85a44138c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GripperMotionGoal)))
  "Returns md5sum for a message object of type 'GripperMotionGoal"
  "083c040d329e25abca99d1f85a44138c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GripperMotionGoal>)))
  "Returns full string definition for message of type '<GripperMotionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%float32 delay ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GripperMotionGoal)))
  "Returns full string definition for message of type 'GripperMotionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%float32 delay ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GripperMotionGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GripperMotionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'GripperMotionGoal
    (cl:cons ':delay (delay msg))
))
