; Auto-generated. Do not edit!


(cl:in-package brl_pxh_api-msg)


;//! \htmlinclude GripperPressureGoal.msg.html

(cl:defclass <GripperPressureGoal> (roslisp-msg-protocol:ros-message)
  ((pressure
    :reader pressure
    :initarg :pressure
    :type cl:float
    :initform 0.0))
)

(cl:defclass GripperPressureGoal (<GripperPressureGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GripperPressureGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GripperPressureGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name brl_pxh_api-msg:<GripperPressureGoal> is deprecated: use brl_pxh_api-msg:GripperPressureGoal instead.")))

(cl:ensure-generic-function 'pressure-val :lambda-list '(m))
(cl:defmethod pressure-val ((m <GripperPressureGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader brl_pxh_api-msg:pressure-val is deprecated.  Use brl_pxh_api-msg:pressure instead.")
  (pressure m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GripperPressureGoal>) ostream)
  "Serializes a message object of type '<GripperPressureGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'pressure))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GripperPressureGoal>) istream)
  "Deserializes a message object of type '<GripperPressureGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'pressure) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GripperPressureGoal>)))
  "Returns string type for a message object of type '<GripperPressureGoal>"
  "brl_pxh_api/GripperPressureGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GripperPressureGoal)))
  "Returns string type for a message object of type 'GripperPressureGoal"
  "brl_pxh_api/GripperPressureGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GripperPressureGoal>)))
  "Returns md5sum for a message object of type '<GripperPressureGoal>"
  "d08eeab8c09d2ba14f8144e3bbf40d21")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GripperPressureGoal)))
  "Returns md5sum for a message object of type 'GripperPressureGoal"
  "d08eeab8c09d2ba14f8144e3bbf40d21")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GripperPressureGoal>)))
  "Returns full string definition for message of type '<GripperPressureGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%float32 pressure ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GripperPressureGoal)))
  "Returns full string definition for message of type 'GripperPressureGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%float32 pressure ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GripperPressureGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GripperPressureGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'GripperPressureGoal
    (cl:cons ':pressure (pressure msg))
))
