; Auto-generated. Do not edit!


(cl:in-package brl_pxh_api-msg)


;//! \htmlinclude JointGroupRadsResult.msg.html

(cl:defclass <JointGroupRadsResult> (roslisp-msg-protocol:ros-message)
  ((log
    :reader log
    :initarg :log
    :type cl:string
    :initform "")
   (success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass JointGroupRadsResult (<JointGroupRadsResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <JointGroupRadsResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'JointGroupRadsResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name brl_pxh_api-msg:<JointGroupRadsResult> is deprecated: use brl_pxh_api-msg:JointGroupRadsResult instead.")))

(cl:ensure-generic-function 'log-val :lambda-list '(m))
(cl:defmethod log-val ((m <JointGroupRadsResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader brl_pxh_api-msg:log-val is deprecated.  Use brl_pxh_api-msg:log instead.")
  (log m))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <JointGroupRadsResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader brl_pxh_api-msg:success-val is deprecated.  Use brl_pxh_api-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <JointGroupRadsResult>) ostream)
  "Serializes a message object of type '<JointGroupRadsResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'log))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'log))
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <JointGroupRadsResult>) istream)
  "Deserializes a message object of type '<JointGroupRadsResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'log) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'log) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<JointGroupRadsResult>)))
  "Returns string type for a message object of type '<JointGroupRadsResult>"
  "brl_pxh_api/JointGroupRadsResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JointGroupRadsResult)))
  "Returns string type for a message object of type 'JointGroupRadsResult"
  "brl_pxh_api/JointGroupRadsResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<JointGroupRadsResult>)))
  "Returns md5sum for a message object of type '<JointGroupRadsResult>"
  "d80d1d6f73b67aee28bf93977c589629")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'JointGroupRadsResult)))
  "Returns md5sum for a message object of type 'JointGroupRadsResult"
  "d80d1d6f73b67aee28bf93977c589629")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<JointGroupRadsResult>)))
  "Returns full string definition for message of type '<JointGroupRadsResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%string log~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'JointGroupRadsResult)))
  "Returns full string definition for message of type 'JointGroupRadsResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%string log~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <JointGroupRadsResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'log))
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <JointGroupRadsResult>))
  "Converts a ROS message object to a list"
  (cl:list 'JointGroupRadsResult
    (cl:cons ':log (log msg))
    (cl:cons ':success (success msg))
))
