// Generated by gencpp from file brl_pxh_api/CartTrajActionGoal.msg
// DO NOT EDIT!


#ifndef BRL_PXH_API_MESSAGE_CARTTRAJACTIONGOAL_H
#define BRL_PXH_API_MESSAGE_CARTTRAJACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <brl_pxh_api/CartTrajGoal.h>

namespace brl_pxh_api
{
template <class ContainerAllocator>
struct CartTrajActionGoal_
{
  typedef CartTrajActionGoal_<ContainerAllocator> Type;

  CartTrajActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  CartTrajActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::brl_pxh_api::CartTrajGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::brl_pxh_api::CartTrajActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brl_pxh_api::CartTrajActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CartTrajActionGoal_

typedef ::brl_pxh_api::CartTrajActionGoal_<std::allocator<void> > CartTrajActionGoal;

typedef boost::shared_ptr< ::brl_pxh_api::CartTrajActionGoal > CartTrajActionGoalPtr;
typedef boost::shared_ptr< ::brl_pxh_api::CartTrajActionGoal const> CartTrajActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brl_pxh_api::CartTrajActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brl_pxh_api::CartTrajActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::brl_pxh_api::CartTrajActionGoal_<ContainerAllocator1> & lhs, const ::brl_pxh_api::CartTrajActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::brl_pxh_api::CartTrajActionGoal_<ContainerAllocator1> & lhs, const ::brl_pxh_api::CartTrajActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace brl_pxh_api

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::brl_pxh_api::CartTrajActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brl_pxh_api::CartTrajActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brl_pxh_api::CartTrajActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brl_pxh_api::CartTrajActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brl_pxh_api::CartTrajActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brl_pxh_api::CartTrajActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brl_pxh_api::CartTrajActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f69f574f638e1aa70aa463e97577cd1";
  }

  static const char* value(const ::brl_pxh_api::CartTrajActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f69f574f638e1aaULL;
  static const uint64_t static_value2 = 0x70aa463e97577cd1ULL;
};

template<class ContainerAllocator>
struct DataType< ::brl_pxh_api::CartTrajActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brl_pxh_api/CartTrajActionGoal";
  }

  static const char* value(const ::brl_pxh_api::CartTrajActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brl_pxh_api::CartTrajActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"CartTrajGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: brl_pxh_api/CartTrajGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"float32 x\n"
"float32 z\n"
"float32 roll\n"
"float32 pitch\n"
"float32 moving_time\n"
"float32 wp_moving_time\n"
"float32 wp_accel_time\n"
"float32 wp_period\n"
;
  }

  static const char* value(const ::brl_pxh_api::CartTrajActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brl_pxh_api::CartTrajActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CartTrajActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brl_pxh_api::CartTrajActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brl_pxh_api::CartTrajActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::brl_pxh_api::CartTrajGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRL_PXH_API_MESSAGE_CARTTRAJACTIONGOAL_H
