// Generated by gencpp from file brl_pxh_api/CartTrajGoal.msg
// DO NOT EDIT!


#ifndef BRL_PXH_API_MESSAGE_CARTTRAJGOAL_H
#define BRL_PXH_API_MESSAGE_CARTTRAJGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace brl_pxh_api
{
template <class ContainerAllocator>
struct CartTrajGoal_
{
  typedef CartTrajGoal_<ContainerAllocator> Type;

  CartTrajGoal_()
    : x(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , moving_time(0.0)
    , wp_moving_time(0.0)
    , wp_accel_time(0.0)
    , wp_period(0.0)  {
    }
  CartTrajGoal_(const ContainerAllocator& _alloc)
    : x(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , moving_time(0.0)
    , wp_moving_time(0.0)
    , wp_accel_time(0.0)
    , wp_period(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _z_type;
  _z_type z;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _moving_time_type;
  _moving_time_type moving_time;

   typedef float _wp_moving_time_type;
  _wp_moving_time_type wp_moving_time;

   typedef float _wp_accel_time_type;
  _wp_accel_time_type wp_accel_time;

   typedef float _wp_period_type;
  _wp_period_type wp_period;





  typedef boost::shared_ptr< ::brl_pxh_api::CartTrajGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brl_pxh_api::CartTrajGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CartTrajGoal_

typedef ::brl_pxh_api::CartTrajGoal_<std::allocator<void> > CartTrajGoal;

typedef boost::shared_ptr< ::brl_pxh_api::CartTrajGoal > CartTrajGoalPtr;
typedef boost::shared_ptr< ::brl_pxh_api::CartTrajGoal const> CartTrajGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brl_pxh_api::CartTrajGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brl_pxh_api::CartTrajGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::brl_pxh_api::CartTrajGoal_<ContainerAllocator1> & lhs, const ::brl_pxh_api::CartTrajGoal_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.z == rhs.z &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.moving_time == rhs.moving_time &&
    lhs.wp_moving_time == rhs.wp_moving_time &&
    lhs.wp_accel_time == rhs.wp_accel_time &&
    lhs.wp_period == rhs.wp_period;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::brl_pxh_api::CartTrajGoal_<ContainerAllocator1> & lhs, const ::brl_pxh_api::CartTrajGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace brl_pxh_api

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::brl_pxh_api::CartTrajGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brl_pxh_api::CartTrajGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brl_pxh_api::CartTrajGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brl_pxh_api::CartTrajGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brl_pxh_api::CartTrajGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brl_pxh_api::CartTrajGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brl_pxh_api::CartTrajGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db3424a7a9bc8795db95e0a23d1c2e25";
  }

  static const char* value(const ::brl_pxh_api::CartTrajGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb3424a7a9bc8795ULL;
  static const uint64_t static_value2 = 0xdb95e0a23d1c2e25ULL;
};

template<class ContainerAllocator>
struct DataType< ::brl_pxh_api::CartTrajGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brl_pxh_api/CartTrajGoal";
  }

  static const char* value(const ::brl_pxh_api::CartTrajGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brl_pxh_api::CartTrajGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"float32 x\n"
"float32 z\n"
"float32 roll\n"
"float32 pitch\n"
"float32 moving_time\n"
"float32 wp_moving_time\n"
"float32 wp_accel_time\n"
"float32 wp_period\n"
;
  }

  static const char* value(const ::brl_pxh_api::CartTrajGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brl_pxh_api::CartTrajGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.z);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.moving_time);
      stream.next(m.wp_moving_time);
      stream.next(m.wp_accel_time);
      stream.next(m.wp_period);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CartTrajGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brl_pxh_api::CartTrajGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brl_pxh_api::CartTrajGoal_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "moving_time: ";
    Printer<float>::stream(s, indent + "  ", v.moving_time);
    s << indent << "wp_moving_time: ";
    Printer<float>::stream(s, indent + "  ", v.wp_moving_time);
    s << indent << "wp_accel_time: ";
    Printer<float>::stream(s, indent + "  ", v.wp_accel_time);
    s << indent << "wp_period: ";
    Printer<float>::stream(s, indent + "  ", v.wp_period);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRL_PXH_API_MESSAGE_CARTTRAJGOAL_H
