// Generated by gencpp from file brl_pxh_api/GripperMotionFeedback.msg
// DO NOT EDIT!


#ifndef BRL_PXH_API_MESSAGE_GRIPPERMOTIONFEEDBACK_H
#define BRL_PXH_API_MESSAGE_GRIPPERMOTIONFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace brl_pxh_api
{
template <class ContainerAllocator>
struct GripperMotionFeedback_
{
  typedef GripperMotionFeedback_<ContainerAllocator> Type;

  GripperMotionFeedback_()
    : log()  {
    }
  GripperMotionFeedback_(const ContainerAllocator& _alloc)
    : log(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _log_type;
  _log_type log;





  typedef boost::shared_ptr< ::brl_pxh_api::GripperMotionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brl_pxh_api::GripperMotionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct GripperMotionFeedback_

typedef ::brl_pxh_api::GripperMotionFeedback_<std::allocator<void> > GripperMotionFeedback;

typedef boost::shared_ptr< ::brl_pxh_api::GripperMotionFeedback > GripperMotionFeedbackPtr;
typedef boost::shared_ptr< ::brl_pxh_api::GripperMotionFeedback const> GripperMotionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brl_pxh_api::GripperMotionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brl_pxh_api::GripperMotionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::brl_pxh_api::GripperMotionFeedback_<ContainerAllocator1> & lhs, const ::brl_pxh_api::GripperMotionFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.log == rhs.log;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::brl_pxh_api::GripperMotionFeedback_<ContainerAllocator1> & lhs, const ::brl_pxh_api::GripperMotionFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace brl_pxh_api

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::brl_pxh_api::GripperMotionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brl_pxh_api::GripperMotionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brl_pxh_api::GripperMotionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brl_pxh_api::GripperMotionFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brl_pxh_api::GripperMotionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brl_pxh_api::GripperMotionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brl_pxh_api::GripperMotionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3e2a6f3c8b4a69b39bb08b44fadcdca";
  }

  static const char* value(const ::brl_pxh_api::GripperMotionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3e2a6f3c8b4a69bULL;
  static const uint64_t static_value2 = 0x39bb08b44fadcdcaULL;
};

template<class ContainerAllocator>
struct DataType< ::brl_pxh_api::GripperMotionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brl_pxh_api/GripperMotionFeedback";
  }

  static const char* value(const ::brl_pxh_api::GripperMotionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brl_pxh_api::GripperMotionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"string log\n"
"\n"
;
  }

  static const char* value(const ::brl_pxh_api::GripperMotionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brl_pxh_api::GripperMotionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.log);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperMotionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brl_pxh_api::GripperMotionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brl_pxh_api::GripperMotionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "log: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.log);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRL_PXH_API_MESSAGE_GRIPPERMOTIONFEEDBACK_H
