// Generated by gencpp from file brl_pxh_api/JointGroupRadsGoal.msg
// DO NOT EDIT!


#ifndef BRL_PXH_API_MESSAGE_JOINTGROUPRADSGOAL_H
#define BRL_PXH_API_MESSAGE_JOINTGROUPRADSGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace brl_pxh_api
{
template <class ContainerAllocator>
struct JointGroupRadsGoal_
{
  typedef JointGroupRadsGoal_<ContainerAllocator> Type;

  JointGroupRadsGoal_()
    : joint_positions()
    , moving_time(0.0)
    , accel_time(0.0)
    , blocking(false)  {
    }
  JointGroupRadsGoal_(const ContainerAllocator& _alloc)
    : joint_positions(_alloc)
    , moving_time(0.0)
    , accel_time(0.0)
    , blocking(false)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _joint_positions_type;
  _joint_positions_type joint_positions;

   typedef float _moving_time_type;
  _moving_time_type moving_time;

   typedef float _accel_time_type;
  _accel_time_type accel_time;

   typedef uint8_t _blocking_type;
  _blocking_type blocking;





  typedef boost::shared_ptr< ::brl_pxh_api::JointGroupRadsGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brl_pxh_api::JointGroupRadsGoal_<ContainerAllocator> const> ConstPtr;

}; // struct JointGroupRadsGoal_

typedef ::brl_pxh_api::JointGroupRadsGoal_<std::allocator<void> > JointGroupRadsGoal;

typedef boost::shared_ptr< ::brl_pxh_api::JointGroupRadsGoal > JointGroupRadsGoalPtr;
typedef boost::shared_ptr< ::brl_pxh_api::JointGroupRadsGoal const> JointGroupRadsGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brl_pxh_api::JointGroupRadsGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brl_pxh_api::JointGroupRadsGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::brl_pxh_api::JointGroupRadsGoal_<ContainerAllocator1> & lhs, const ::brl_pxh_api::JointGroupRadsGoal_<ContainerAllocator2> & rhs)
{
  return lhs.joint_positions == rhs.joint_positions &&
    lhs.moving_time == rhs.moving_time &&
    lhs.accel_time == rhs.accel_time &&
    lhs.blocking == rhs.blocking;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::brl_pxh_api::JointGroupRadsGoal_<ContainerAllocator1> & lhs, const ::brl_pxh_api::JointGroupRadsGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace brl_pxh_api

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::brl_pxh_api::JointGroupRadsGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brl_pxh_api::JointGroupRadsGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brl_pxh_api::JointGroupRadsGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brl_pxh_api::JointGroupRadsGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brl_pxh_api::JointGroupRadsGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brl_pxh_api::JointGroupRadsGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brl_pxh_api::JointGroupRadsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a60ad48bfbf8b530fe8dd3f8c58bce45";
  }

  static const char* value(const ::brl_pxh_api::JointGroupRadsGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa60ad48bfbf8b530ULL;
  static const uint64_t static_value2 = 0xfe8dd3f8c58bce45ULL;
};

template<class ContainerAllocator>
struct DataType< ::brl_pxh_api::JointGroupRadsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brl_pxh_api/JointGroupRadsGoal";
  }

  static const char* value(const ::brl_pxh_api::JointGroupRadsGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brl_pxh_api::JointGroupRadsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"float32[] joint_positions\n"
"float32 moving_time\n"
"float32 accel_time\n"
"bool blocking\n"
;
  }

  static const char* value(const ::brl_pxh_api::JointGroupRadsGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brl_pxh_api::JointGroupRadsGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_positions);
      stream.next(m.moving_time);
      stream.next(m.accel_time);
      stream.next(m.blocking);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointGroupRadsGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brl_pxh_api::JointGroupRadsGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brl_pxh_api::JointGroupRadsGoal_<ContainerAllocator>& v)
  {
    s << indent << "joint_positions[]" << std::endl;
    for (size_t i = 0; i < v.joint_positions.size(); ++i)
    {
      s << indent << "  joint_positions[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joint_positions[i]);
    }
    s << indent << "moving_time: ";
    Printer<float>::stream(s, indent + "  ", v.moving_time);
    s << indent << "accel_time: ";
    Printer<float>::stream(s, indent + "  ", v.accel_time);
    s << indent << "blocking: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.blocking);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRL_PXH_API_MESSAGE_JOINTGROUPRADSGOAL_H
