// Generated by gencpp from file brl_pxh_api/JointRadGoal.msg
// DO NOT EDIT!


#ifndef BRL_PXH_API_MESSAGE_JOINTRADGOAL_H
#define BRL_PXH_API_MESSAGE_JOINTRADGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace brl_pxh_api
{
template <class ContainerAllocator>
struct JointRadGoal_
{
  typedef JointRadGoal_<ContainerAllocator> Type;

  JointRadGoal_()
    : joint_name()
    , position(0.0)
    , moving_time(0.0)
    , accel_time(0.0)
    , blocking(false)  {
    }
  JointRadGoal_(const ContainerAllocator& _alloc)
    : joint_name(_alloc)
    , position(0.0)
    , moving_time(0.0)
    , accel_time(0.0)
    , blocking(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _joint_name_type;
  _joint_name_type joint_name;

   typedef float _position_type;
  _position_type position;

   typedef float _moving_time_type;
  _moving_time_type moving_time;

   typedef float _accel_time_type;
  _accel_time_type accel_time;

   typedef uint8_t _blocking_type;
  _blocking_type blocking;





  typedef boost::shared_ptr< ::brl_pxh_api::JointRadGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brl_pxh_api::JointRadGoal_<ContainerAllocator> const> ConstPtr;

}; // struct JointRadGoal_

typedef ::brl_pxh_api::JointRadGoal_<std::allocator<void> > JointRadGoal;

typedef boost::shared_ptr< ::brl_pxh_api::JointRadGoal > JointRadGoalPtr;
typedef boost::shared_ptr< ::brl_pxh_api::JointRadGoal const> JointRadGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brl_pxh_api::JointRadGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brl_pxh_api::JointRadGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::brl_pxh_api::JointRadGoal_<ContainerAllocator1> & lhs, const ::brl_pxh_api::JointRadGoal_<ContainerAllocator2> & rhs)
{
  return lhs.joint_name == rhs.joint_name &&
    lhs.position == rhs.position &&
    lhs.moving_time == rhs.moving_time &&
    lhs.accel_time == rhs.accel_time &&
    lhs.blocking == rhs.blocking;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::brl_pxh_api::JointRadGoal_<ContainerAllocator1> & lhs, const ::brl_pxh_api::JointRadGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace brl_pxh_api

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::brl_pxh_api::JointRadGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brl_pxh_api::JointRadGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brl_pxh_api::JointRadGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brl_pxh_api::JointRadGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brl_pxh_api::JointRadGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brl_pxh_api::JointRadGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brl_pxh_api::JointRadGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4e2eff58f579aff3380de47294f5becc";
  }

  static const char* value(const ::brl_pxh_api::JointRadGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4e2eff58f579aff3ULL;
  static const uint64_t static_value2 = 0x380de47294f5beccULL;
};

template<class ContainerAllocator>
struct DataType< ::brl_pxh_api::JointRadGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brl_pxh_api/JointRadGoal";
  }

  static const char* value(const ::brl_pxh_api::JointRadGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brl_pxh_api::JointRadGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"string joint_name\n"
"float32 position\n"
"float32 moving_time\n"
"float32 accel_time\n"
"bool blocking \n"
;
  }

  static const char* value(const ::brl_pxh_api::JointRadGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brl_pxh_api::JointRadGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_name);
      stream.next(m.position);
      stream.next(m.moving_time);
      stream.next(m.accel_time);
      stream.next(m.blocking);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointRadGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brl_pxh_api::JointRadGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brl_pxh_api::JointRadGoal_<ContainerAllocator>& v)
  {
    s << indent << "joint_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.joint_name);
    s << indent << "position: ";
    Printer<float>::stream(s, indent + "  ", v.position);
    s << indent << "moving_time: ";
    Printer<float>::stream(s, indent + "  ", v.moving_time);
    s << indent << "accel_time: ";
    Printer<float>::stream(s, indent + "  ", v.accel_time);
    s << indent << "blocking: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.blocking);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRL_PXH_API_MESSAGE_JOINTRADGOAL_H
