# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from brl_pxh_api/EePoseCompGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class EePoseCompGoal(genpy.Message):
  _md5sum = "7d4193829330657a5eee6b3438daef12"
  _type = "brl_pxh_api/EePoseCompGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# Goal
float32 x
float32 z
float32 roll
float32 pitch
bool execute
float32 moving_time
float32 accel_time 
bool blocking
"""
  __slots__ = ['x','z','roll','pitch','execute','moving_time','accel_time','blocking']
  _slot_types = ['float32','float32','float32','float32','bool','float32','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,z,roll,pitch,execute,moving_time,accel_time,blocking

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EePoseCompGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0.
      if self.z is None:
        self.z = 0.
      if self.roll is None:
        self.roll = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.execute is None:
        self.execute = False
      if self.moving_time is None:
        self.moving_time = 0.
      if self.accel_time is None:
        self.accel_time = 0.
      if self.blocking is None:
        self.blocking = False
    else:
      self.x = 0.
      self.z = 0.
      self.roll = 0.
      self.pitch = 0.
      self.execute = False
      self.moving_time = 0.
      self.accel_time = 0.
      self.blocking = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4fB2fB().pack(_x.x, _x.z, _x.roll, _x.pitch, _x.execute, _x.moving_time, _x.accel_time, _x.blocking))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 26
      (_x.x, _x.z, _x.roll, _x.pitch, _x.execute, _x.moving_time, _x.accel_time, _x.blocking,) = _get_struct_4fB2fB().unpack(str[start:end])
      self.execute = bool(self.execute)
      self.blocking = bool(self.blocking)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4fB2fB().pack(_x.x, _x.z, _x.roll, _x.pitch, _x.execute, _x.moving_time, _x.accel_time, _x.blocking))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 26
      (_x.x, _x.z, _x.roll, _x.pitch, _x.execute, _x.moving_time, _x.accel_time, _x.blocking,) = _get_struct_4fB2fB().unpack(str[start:end])
      self.execute = bool(self.execute)
      self.blocking = bool(self.blocking)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4fB2fB = None
def _get_struct_4fB2fB():
    global _struct_4fB2fB
    if _struct_4fB2fB is None:
        _struct_4fB2fB = struct.Struct("<4fB2fB")
    return _struct_4fB2fB
